# Generated by Django 5.1.3 on 2025-01-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('sport', 'Sport'), ('clothing', 'Clothing'), ('miscellaneous', 'Miscellaneous')], max_length=64),
        ),
    ]
