# Generated by Django 5.1.3 on 2025-01-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_bidder_bid_listing_listing_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(default='', max_length=128),
        ),
    ]
