# Generated by Django 5.1.3 on 2025-01-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_image_url_followed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='current_bid',
            new_name='price',
        ),
    ]
