# Generated by Django 5.1.3 on 2025-01-19 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_current_bid_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
